### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by DonyorM** [boot-clj/boot-figreload#12]
I'm trying to run a project with boot-figreload, and getting a fairly cryptic error when I run it. Below is the error and [here](https://gist.github.com/e588ef18d5265d1749f85b338ef98da2) is the build.boot file. Any idea what is causing this?

```
>boot -vv figwheel
....
clojure.lang.ExceptionInfo: null {:line 146}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at boot.main$_main$fn__1201.invoke(main.clj:222)
	at boot.main$_main.invoke(main.clj:216)
	at clojure.lang.Var.invoke(Var.java:394)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:159)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:150)
	at boot.App.runBoot(App.java:399)
	at boot.App.main(App.java:491)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Boot.main(Boot.java:258)
Caused by: java.lang.NullPointerException
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at boot.user$eval1302$fn__1303$fn__1308$fn__1309.invoke(Unknown Source)
	at adzerk.boot_cljs$eval1001$fn__1002$fn__1007$fn__1008.invoke(boot_cljs.clj:250)
	at adzerk.boot_cljs$eval946$fn__947$fn__952$fn__953.invoke(boot_cljs.clj:169)
	at adzerk.boot_cljs_repl$eval1104$fn__1105$fn__1114$fn__1115.invoke(boot_cljs_repl.clj:187)
	at boot.task.built_in$fn__2136$fn__2137$fn__2154$fn__2155.invoke(built_in.clj:491)
	at boot.task.built_in$fn__2136$fn__2137$fn__2146$fn__2147.invoke(built_in.clj:489)
	at powerlaces.boot_figreload$eval2099$fn__2100$fn__2109$fn__2110$fn__2118.invoke(boot_figreload.clj:221)
	at powerlaces.boot_figreload$eval2099$fn__2100$fn__2109$fn__2110.invoke(boot_figreload.clj:220)
	at boot.core$run_tasks.invoke(core.clj:1021)
	at boot.core$boot$fn__933.invoke(core.clj:1031)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by arichiardi** [comment]
Oh that's very dense..do you have a .cljs.edn? What is the content?

**Comment by DonyorM** [comment]
Just figured it out. I accidentally named the project "boot" (I was testing the boot profile for luminus, so it kinda made sense), which resulted in a project namespace "boot.core", which of course broke everything. A different namespace name worked fine.

Sorry to waste your time. Thanks for your help anyway.

**Comment by arichiardi** [comment]
On no waste, glad you figured it out!
